version: '3'
services:
  server:
    image: panchem/ctrack-server
    labels:
      - 'traefik.backend=be'
      - 'traefik.docker.network=proxy'
      - 'traefik.enable=true'
      - 'traefik.port=3400'
      - 'traefik.frontend.rule=PathPrefixStrip:/api/'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.priority=20'
  ui:
    image: panchem/ctrack-ui
    labels:
      - 'traefik.backend=ui'
      - 'traefik.docker.network=proxy'
      - 'traefik.frontend.rule=Host:ctrack.panchem.io'
      - 'traefik.enable=true'
      - 'traefik.port=80'
      - 'traefik.default.protocol=http'
      - 'traefik.frontend.priority=10'
  redis:
    image: redis:4-alpine

networks:
  default:
    external:
      name: proxy
